### ISSUE TITLE
Course Card should update per search

### ISSUE THREAD

**Issue by jhcccc** [Deerhound579/mcgill-course-map#3]
![reddit](https://user-images.githubusercontent.com/8275280/69010413-93702500-092d-11ea-96b4-b13458bbf652.png)
Mentioned on Reddit. The course card doesn't automatically update per new search. But user would expect auto-updates. Maybe update the card per search for better UX.

**Comment by Deerhound579** [comment]
I already looked into that, but from Dash's FAQ:
> A component/property pair can only be the Output of one callback

I'll see if I can bundle them into a larger callback in a not-so-ugly way.
